# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='deadline',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
