# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0002_column_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
