# Generated by Django 2.2.2 on 2019-08-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0006_column_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_example',
            field=models.BooleanField(default=False),
        ),
    ]
