# Generated by Django 2.2.2 on 2019-08-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0007_column_is_example'),
        ('columns', '0007_auto_20190814_0347'),
    ]

    operations = [
    ]
