# Generated by Django 2.2.2 on 2019-08-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0008_merge_20190818_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
