# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        ('users_goals_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_goals_categories.User_Goal_Category')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Goal')),
            ],
        ),
    ]
