# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_goals_categories', '0001_initial'),
        ('goals', '0001_initial'),
        ('goals_categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal_category',
            name='category',
        ),
        migrations.AddField(
            model_name='goal_category',
            name='category',
            field=models.ManyToManyField(to='users_goals_categories.User_Goal_Category'),
        ),
        migrations.RemoveField(
            model_name='goal_category',
            name='goal',
        ),
        migrations.AddField(
            model_name='goal_category',
            name='goal',
            field=models.ManyToManyField(to='goals.Goal'),
        ),
    ]
