# Generated by Django 2.2.2 on 2019-07-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('tasks', '0003_auto_20190727_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='checklist',
        ),
        migrations.AddField(
            model_name='task',
            name='checklist',
            field=models.ManyToManyField(to='checklists.Checklist'),
        ),
    ]
