# Generated by Django 2.2.2 on 2019-07-30 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('tasks', '0004_auto_20190729_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='checklist',
        ),
        migrations.AddField(
            model_name='task',
            name='checklist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='checklists.Checklist'),
        ),
    ]
