# Generated by Django 2.2.2 on 2019-08-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190729_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checklist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='checklists.Checklist'),
        ),
    ]
