# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPropertyFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_budget', models.FloatField()),
                ('moving_date', models.DateField(null=True)),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property_types.Property_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
