# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_property_filter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPropertyFilter',
            new_name='User_property_filter',
        ),
    ]
