# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_property_filter', '0003_auto_20181228_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_property_filter',
            name='rent_anywhere',
            field=models.BooleanField(default=True),
        ),
    ]
