# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_property_filter', '0004_user_property_filter_rent_anywhere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_property_filter',
            name='property_type',
        ),
    ]
