# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_property_filter', '0005_remove_user_property_filter_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_property_filter',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
