# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='current_property_has_bedbugs',
            new_name='current_property_has_infestations',
        ),
    ]
