# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_types', '0001_initial'),
        ('user_property_filter', '0005_remove_user_property_filter_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_property_filter_property_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_property_filter.User_property_filter')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_types.Property_type')),
            ],
        ),
    ]
