# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
                ('sqft', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('rental_value', models.FloatField()),
                ('utilities_included', models.BooleanField()),
                ('n_bedrooms', models.IntegerField()),
                ('n_bathrooms', models.IntegerField()),
                ('address', models.TextField()),
                ('furnished', models.BooleanField()),
                ('no_pets', models.BooleanField()),
                ('no_smoking', models.BooleanField()),
                ('no_parties', models.BooleanField()),
                ('minimum_lease', models.IntegerField()),
                ('pet_deposit', models.FloatField()),
                ('security_deposit', models.FloatField()),
                ('publication_date', models.DateTimeField()),
                ('available_to_mode_in_date', models.DateField()),
                ('open_view_start', models.DateTimeField()),
                ('open_view_end', models.DateTimeField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
