# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('properties', '0001_initial'), ('properties', '0002_auto_20181020_0011'), ('properties', '0003_auto_20181020_0013'), ('properties', '0004_auto_20181020_0015'), ('properties', '0005_auto_20181020_0021'), ('properties', '0006_property_upload'), ('properties', '0007_auto_20181020_1845'), ('properties', '0008_auto_20181020_1849'), ('properties', '0009_auto_20181020_2318'), ('properties', '0010_property_utilities_estimation'), ('properties', '0011_property_description'), ('properties', '0012_auto_20181201_1101'), ('properties', '0013_auto_20181201_1138'), ('properties', '0014_remove_property_upload')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighborhoods', '0003_auto_20181114_1830'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('sqft', models.IntegerField()),
                ('type', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='property_types.Property_type')),
                ('rental_value', models.FloatField()),
                ('utilities_included', models.BooleanField()),
                ('n_bedrooms', models.IntegerField()),
                ('n_bathrooms', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('furnished', models.BooleanField()),
                ('no_pets', models.BooleanField()),
                ('no_smoking', models.BooleanField()),
                ('no_parties', models.BooleanField()),
                ('minimum_lease', models.IntegerField()),
                ('pet_deposit', models.FloatField()),
                ('security_deposit', models.FloatField()),
                ('publication_date', models.DateTimeField()),
                ('available_to_move_in_date', models.DateField()),
                ('open_view_start', models.DateTimeField()),
                ('open_view_end', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('utilities_estimation', models.FloatField(default=0)),
                ('description', models.TextField(default='')),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cities.City')),
                ('neighborhood', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.Neighborhood')),
            ],
        ),
    ]
