# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_squashed_0014_remove_property_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='phone',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
