# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20181020_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='property_types.Property_type'),
        ),
    ]
