# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='phone',
        ),
    ]
