# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20181020_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
