# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20181020_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='available_to_mode_in_date',
            new_name='available_to_move_in_date',
        ),
    ]
