# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 18:45
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='property',
            name='upload',
            field=stdimage.models.StdImageField(blank=True, upload_to='static/images/properties/<function property_directory_path at 0x7f85f755c1e0>'),
        ),
    ]
