# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 23:18
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20181020_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='upload',
            field=stdimage.models.StdImageField(blank=True, upload_to='static/images/properties'),
        ),
    ]
