# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20181020_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='utilities_estimation',
            field=models.FloatField(default=0),
        ),
    ]
