# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_utilities_estimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
