# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('neighborhoods', '0003_auto_20181114_1830'),
        ('properties', '0011_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.Neighborhood'),
        ),
    ]
