# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20181201_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.Neighborhood'),
        ),
    ]
