# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20181201_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='upload',
        ),
    ]
