# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0002_auto_20181114_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
