# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0008_auto_20181226_1610'),
        ('neighborhoods', '0003_auto_20181114_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.Neighborhood')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.Resume')),
            ],
        ),
    ]
