# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('provinces', '0002_province_abbrev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='abbrev',
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
            preserve_default=False,
        ),
    ]
