# Generated by Django 2.2.2 on 2019-08-05 16:56

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_mediafile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(max_length=255, upload_to='', validators=[apps.documents.models.validate_file_extension]),
        ),
    ]
