# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('resumes', '0002_auto_20180930_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
        ),
    ]
