# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
