# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='consent_credit_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='consent_criminal_check',
            field=models.BooleanField(default=True),
        ),
    ]
