# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_auto_20181027_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='total_household_income',
            field=models.FloatField(default=0),
        ),
    ]
