# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_auto_20181226_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
