# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_auto_20190101_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='current_wage',
            field=models.FloatField(default=0),
        ),
    ]
