# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_auto_20190102_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
