# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column_goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='columns.Column')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Goal')),
            ],
        ),
    ]
