# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('columns', '0001_initial'),
        ('columns_goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column_goal',
            name='column',
        ),
        migrations.AddField(
            model_name='column_goal',
            name='column',
            field=models.ManyToManyField(to='columns.Column'),
        ),
        migrations.RemoveField(
            model_name='column_goal',
            name='goal',
        ),
        migrations.AddField(
            model_name='column_goal',
            name='goal',
            field=models.ManyToManyField(to='goals.Goal'),
        ),
    ]
