# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190123_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='type',
        ),
    ]
