# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_board_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
