# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(null=1),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(null=1),
        ),
    ]
