# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-25 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('users', '0008_remove_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='labels',
            field=models.ManyToManyField(default=None, null=True, to='labels.Label'),
        ),
    ]
