# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-25 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190525_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='labels',
        ),
    ]
