# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_of_knowledges', '0001_initial'),
        ('users', '0011_remove_user_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areas_of_knowledge',
            field=models.ManyToManyField(to='area_of_knowledges.Area_of_knowledge'),
        ),
    ]
