# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0003_goal_status'),
        ('boards', '0002_auto_20190123_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ManyToManyField(to='boards.Board')),
                ('goal', models.ManyToManyField(to='goals.Goal')),
            ],
        ),
    ]
