# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0003_auto_20180930_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='abbrev',
            field=models.CharField(default='', max_length=255),
        ),
    ]
