# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='value',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
