# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20181027_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
    ]
