# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20181028_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 11, 13, 35, 868678)),
        ),
    ]
