# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 18:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20181028_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 18, 15, 50, 924838, tzinfo=utc)),
        ),
    ]
