# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20181028_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
