# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='abbrev',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
