# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('columns', '0001_initial'),
        ('users_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(to='users_categories.User_Category')),
                ('column', models.ManyToManyField(to='columns.Column')),
            ],
        ),
    ]
