# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='column_day',
        ),
    ]
