# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_auto_20190213_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
