# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_auto_20190501_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
