# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_auto_20190512_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(),
        ),
    ]
