# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-18 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_goal_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
