# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_goal_order_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='order_position',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
