# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-22 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_auto_20190621_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentvote', to='goals.GoalComment'),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='downvote',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='upvote',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='goalcomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
