# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_auto_20190621_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalcomment',
            name='vote',
        ),
    ]
