# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_auto_20190621_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
