# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_remove_goalcomment_vote'),
        ('goals', '0014_auto_20190625_2213'),
    ]

    operations = [
    ]
