# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0016_merge_20190626_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
