# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 02:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0017_auto_20190704_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='member',
            field=models.ManyToManyField(related_name='goal_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
