# Generated by Django 2.2.2 on 2019-07-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0018_goal_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='order_position',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
