# Generated by Django 2.2.2 on 2019-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0019_auto_20190721_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
