# Generated by Django 2.2.2 on 2019-08-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20190805_0958'),
        ('goals', '0019_auto_20190721_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.MediaFile'),
        ),
    ]
