# Generated by Django 2.2.2 on 2019-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0020_goal_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='duration_hrs',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
