# Generated by Django 2.2.2 on 2019-08-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20190811_0029'),
        ('goals', '0022_auto_20190814_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='file',
        ),
        migrations.AddField(
            model_name='goal',
            name='file',
            field=models.ManyToManyField(default=None, to='documents.MediaFile'),
        ),
    ]
